name: SSH Command
run-name: ${{ github.actor }} is testing out GitHub Actions remote interaction 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSH Command
        env:
          PRODUCTION_HOST: ${{ vars.PRODUCTION_HOST }}
          PRODUCTION_USER_NAME: ${{ secrets.PRODUCTION_USER_NAME }}
          PRODUCTION_USER_PASSWORD: ${{ secrets.PRODUCTION_USER_PASSWORD }}
        run: |
          sshpass -p "$PRODUCTION_USER_PASSWORD" ssh -o StrictHostKeyChecking=no $PRODUCTION_USER_NAME@$PRODUCTION_HOST "cd ./project && echo 'text' >> file.txt"