name: GitHub Actions Demo

on: push

jobs:
  build:
    if: ${{ github.event.label.name == 'deploy/production' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo PUSHED!!